["CODE_OF_CONDUCT.md"]
append = """
Furthermore, on the Julia-specific repos and website sections, do not sexualize or genderize the term "Julia" or any other aspects of the project.
While "Julia" is a female name in many parts of the world, the programming language is not a person and does not have a gender.
"""
